// ── Holiday data ─────────────────────────────────────────────
// Public holidays ship with the site (data/holidays/<CC>.json, generated by
// tools/build-holidays.cjs from date-holidays). Nothing leaves the page: a
// country's file is fetched from this origin the first time a plan names it,
// then the plan re-renders. The lookup is what calendar.js consumes.

const files = new Map()      // code -> { years } | 'loading' | 'failed'
let index = null             // [{ code, name }]
let onLoaded = () => {}

export const cal = {
  holidays(code, year) {
    const f = files.get(code)
    return f && typeof f === 'object' ? f.years[year] || [] : null
  },
  status(code) {
    const f = files.get(code)
    return !f ? 'none' : typeof f === 'string' ? f : 'ok'
  },
}

/** Call once: the repaint to run whenever a calendar arrives. */
export function onHolidays(fn) { onLoaded = fn }

/** Fetch every calendar the plan needs that is not here yet. Safe to call on every render. */
export function ensureHolidays(codes) {
  for (const code of codes) {
    if (!code || files.has(code) || !/^[A-Z]{2}$/.test(code)) continue
    files.set(code, 'loading')
    fetch(`data/holidays/${code}.json`)
      .then(r => (r.ok ? r.json() : Promise.reject(new Error(r.status))))
      .then(d => { files.set(code, { years: d.years || {} }) })
      .catch(() => { files.set(code, 'failed') })
      .finally(() => onLoaded())
  }
}

/** The country list for the pickers, loaded once. */
export async function loadIndex() {
  if (index) return index
  try {
    const r = await fetch('data/holidays/index.json')
    index = r.ok ? (await r.json()).countries : []
  } catch { index = [] }
  return index
}
export const countries = () => index || []

/** Pinned first in every picker, in this order: the teams Reparto is planned for. */
export const MAIN = ['US', 'CO', 'CL', 'PE', 'AR', 'MX']
const SHORT = { US: 'United States', GB: 'United Kingdom' }

export function countryName(code) {
  if (!code) return ''
  return SHORT[code] || countries().find(c => c.code === code)?.name || code
}
