// Regenerate js/icon-data.js from the lucide-static package.
//
// The page draws every icon inline from that one generated map, so there is
// no icon font, no sprite request and no library at runtime. Add a name to
// NAMES and rerun:
//
//   npm install --prefix "$TMPDIR/lucide" lucide-static@1
//   NODE_PATH="$TMPDIR/lucide/node_modules" node tools/build-icons.cjs
//
// Icons: Lucide (https://lucide.dev), ISC licence.

const fs = require('fs')
const path = require('path')

const pkgPath = require.resolve('lucide-static/package.json')
const pkg = require(pkgPath)
const DIR = path.join(path.dirname(pkgPath), 'icons')

const NAMES = [
  // statuses
  'circle-check', 'circle-arrow-down', 'circle-arrow-up', 'circle-help', 'user-x', 'triangle-alert', 'octagon-alert', 'info',
  // carrying and dropping
  'hand-grab', 'circle-plus', 'move',
  // people
  'tree-palm', 'plane', 'user-search', 'user-plus', 'users', 'pin', 'flame',
  // deliverables
  'sticky-note', 'calendar-clock', 'archive', 'ellipsis', 'trash-2', 'pencil', 'rotate-ccw', 'target', 'calendar-check',
  // header and menus
  'layers', 'download', 'eraser', 'undo-2', 'redo-2', 'link', 'sheet', 'file-text', 'file-json', 'file-up', 'copy', 'plus', 'history', 'lightbulb', 'check', 'x',
  // views
  'layout-grid', 'table-2', 'chevron-up', 'chevron-down', 'arrow-up-down',
]

const out = {}
for (const name of NAMES) {
  const svg = fs.readFileSync(path.join(DIR, `${name}.svg`), 'utf8')
  const inner = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '')
  out[name] = inner.replace(/\s*\n\s*/g, '').replace(/\s+\/>/g, '/>').trim()
}

const body = Object.entries(out).map(([k, v]) => `  '${k}': '${v}',`).join('\n')
fs.writeFileSync(path.join(__dirname, '..', 'js', 'icon-data.js'),
`// Generated by tools/build-icons.cjs from lucide-static ${pkg.version}. Do not edit:
// add a name there and rerun \`make icons\`. Icons: Lucide, ISC licence.
export const ICONS = {
${body}
}
`)
console.log(`${NAMES.length} icons from lucide-static ${pkg.version}`)
